"""empty message

Revision ID: 09ab10a96718
Revises: 61a2061ece8e
Create Date: 2016-12-18 12:58:33.845761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ab10a96718'
down_revision = '61a2061ece8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
