"""empty message

Revision ID: c6c4e82e21f0
Revises: 5ccc1632dc15
Create Date: 2016-12-15 14:48:15.714582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c4e82e21f0'
down_revision = '5ccc1632dc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disliked_genres')
    op.drop_column('users', 'interested_events')
    op.drop_column('users', 'disliked_artists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disliked_artists', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('interested_events', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('disliked_genres', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
